"""
edge_error.py
======================================================================
Edge (route-level) error for SUMO map-matching output, using the
Newson & Krumm accuracy metric:

    accuracy = (d+ + d-) / d0

    d0  = length of the correct (ground-truth) route
    d-  = length of correct-route segments the matcher MISSED
          ("erroneously subtracted")
    d+  = length of matched-route segments that AREN'T on the correct
          route ("erroneously added")

WHERE THE GROUND-TRUTH ROUTE COMES FROM
-----------------------------------------
Newson & Krumm's ground truth is a known, ordered sequence of road
edges -- exactly what a SUMO <route edges="..."/> already is. That's
full_campus_v2_rou.xml: the eBike's ground-truth trace (the gt_x/gt_y
columns in the matched CSVs) was generated by simulating THIS route, so
its edge list already IS the correct route that d0/d-/d+ are measured
against.

THE PROBLEM YOU FLAGGED -- AND WHY IT TURNS OUT NOT TO BE ONE
-----------------------------------------------------------------
You mentioned not having GPS coordinates for each ground-truth edge, on
the assumption the metric needs to look at individual points to decide
which edge each one "should" be on. It doesn't, in this formulation:
Newson & Krumm's accuracy is a comparison between two ROUTES (ordered
edge lists), not something done point-by-point. You already have both
routes as edge-ID lists, with no GPS coordinates involved at all:

  - the correct route:  the <route edges="..."/> in the rou.xml
  - the matched route:  the edge_id column your matching pipeline
                         already wrote to every row of the matched CSV,
                         collapsed into the sequence of distinct edges
                         actually traversed (see edges_from_matched_csv)

The only per-edge information the metric needs is each edge's LENGTH,
which comes from the network file (net.xml) via sumolib -- not from any
GPS point, ground-truth or otherwise.

If you still want the ground-truth route's own geometry as lat/lon
(e.g. to plot it against the raw phone trace, or to sanity-check that
the recorded ride really followed this route), set
EXPORT_GROUND_TRUTH_GEOMETRY = True below. export_ground_truth_geometry
builds that CSV by walking each ground-truth edge's shape through the
network's own coordinate conversion -- literally "GPS coordinates for
each edge" -- but it's a bonus and isn't used by the accuracy
calculation itself.

No command-line arguments: edit the CONFIG block below and re-run.
----------------------------------------------------------------------
"""

import os
import sys
import csv
from collections import Counter
import xml.etree.ElementTree as ET

# ---------- EDIT THIS ----------
# Point straight at a .net.xml, OR leave NET_FILE as None and point
# SUMOCFG at the .sumocfg -- the net file is then read out of it, same
# as post_processed_matching_v2.py does.
NET_FILE = None
SUMOCFG = r"2026-03-11-17-20-46/osm.sumocfg"  # update to match your scenario

ROUTE_FILE = "2026-03-11-17-20-46/full_campus_v2.rou.xml"
# Which <route id="..."> counts as ground truth. Leave as None to
# auto-pick when the file defines exactly one route (this project's
# file does); set it explicitly if the file ever defines more than one.
ROUTE_ID = None

# label -> path, same convention as positional_error.py. Paths are
# relative to this script's own directory unless absolute.
FILES = {
    "native":        "Data/Unfiltered Outputs/matched_native_20260905-195657.csv",
    "native_kalman": "Data/Filtered Outputs/matched_native_kalman_20260905-194946.csv",
    "topo":          "Data/Unfiltered Outputs/matched_topo_20260905-195705.csv",
    "topo_kalman":   "Data/Filtered Outputs/matched_topo_kalman_20260905-194415.csv",
    "fuzzy":         "Data/Unfiltered Outputs/matched_fuzzy_20260905-195714.csv",
    "fuzzy_kalman":  "Data/Filtered Outputs/matched_fuzzy_kalman_20260905-194958.csv",
    "hmm":           "Data/Unfiltered Outputs/matched_hmm_20260905-195724.csv",
    "hmm_kalman":    "Data/Filtered Outputs/matched_hmm_kalman_20260905-195319.csv",
    "st":            "Data/Unfiltered Outputs/matched_st_20260905-195733.csv",
    "st_kalman":     "Data/Filtered Outputs/matched_st_kalman_20260905-195604.csv",
}

# Junction/connector edges (IDs starting with ":") aren't part of a SUMO
# route definition, so they're dropped from the matched sequence too --
# otherwise every turn through an intersection would spuriously count
# as an "extra" edge relative to the ground truth.
EXCLUDE_INTERNAL_EDGES = True

SUMMARY_OUTPUT = "Data/edge_error_summary.csv"

# See "THE PROBLEM YOU FLAGGED" above -- a bonus, not required for the
# accuracy numbers.
EXPORT_GROUND_TRUTH_GEOMETRY = True
GROUND_TRUTH_GEOMETRY_OUTPUT = "Data/ground_truth_route_geometry.csv"
# --------------------------------

if "SUMO_HOME" not in os.environ:
    raise EnvironmentError("SUMO_HOME is not set. Set it before running this script.")

SUMO_HOME = os.environ["SUMO_HOME"]
TOOLS = os.path.join(SUMO_HOME, "tools")
if TOOLS not in sys.path:
    sys.path.append(TOOLS)

import sumolib  # noqa: E402

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def _resolve(path):
    return path if os.path.isabs(path) else os.path.join(SCRIPT_DIR, path)


def parse_sumocfg_for_netfile(sumocfg_path: str) -> str:
    """Read the .sumocfg XML and return the absolute path to its
    <net-file>, resolved relative to the config's own directory."""
    tree = ET.parse(sumocfg_path)
    root = tree.getroot()

    input_tag = root.find("input")
    if input_tag is None:
        raise ValueError(f"No <input> section found in {sumocfg_path}")

    net_tag = input_tag.find("net-file")
    if net_tag is None:
        raise ValueError(f"No <net-file> entry found in {sumocfg_path}")

    net_value = net_tag.get("value")
    if not net_value:
        raise ValueError(f"net-file has no value in {sumocfg_path}")

    base_dir = os.path.dirname(os.path.abspath(sumocfg_path))
    return os.path.abspath(os.path.join(base_dir, net_value))


def load_ground_truth_route(route_file, route_id=None):
    """Parse a SUMO .rou.xml and return the ground-truth route as an
    ordered list of edge IDs. Picks the sole <route> automatically when
    the file only defines one (as full_campus_v2_rou.xml does); raises
    with the available IDs if the file defines several and none was
    named."""
    tree = ET.parse(route_file)
    root = tree.getroot()
    routes = root.findall(".//route")
    if not routes:
        raise ValueError(f"No <route> elements found in {route_file}")

    if route_id is not None:
        for r in routes:
            if r.get("id") == route_id:
                return r.get("edges", "").split()
        available = ", ".join(r.get("id", "<no id>") for r in routes)
        raise ValueError(f"No route with id '{route_id}' in {route_file}. "
                          f"Available: {available}")

    if len(routes) == 1:
        return routes[0].get("edges", "").split()

    available = ", ".join(r.get("id", "<no id>") for r in routes)
    raise ValueError(f"{route_file} defines {len(routes)} routes; set ROUTE_ID "
                      f"to one of: {available}")


def _is_true(value):
    return str(value).strip().lower() in ("true", "1", "yes")


def edges_from_matched_csv(csv_path, exclude_internal=True):
    """Return the matched route as an ordered list of edge IDs: the
    edge_id column, restricted to matched/non-internal rows, with
    consecutive repeats collapsed. A vehicle sitting on the same edge
    across several consecutive GPS fixes should count as ONE edge
    traversal, not one per fix -- only a genuine change of edge is a new
    step in the route."""
    route = []
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        if "edge_id" not in (reader.fieldnames or []):
            raise ValueError(f"{csv_path} has no 'edge_id' column.")
        for row in reader:
            if "matched" in row and not _is_true(row["matched"]):
                continue
            edge_id = row.get("edge_id", "")
            if not edge_id:
                continue
            if exclude_internal and edge_id.startswith(":"):
                continue
            if not route or route[-1] != edge_id:
                route.append(edge_id)
    return route


def edge_lengths(net, edge_ids):
    """Look up each edge's length via sumolib. A missing edge ID (e.g. a
    stale one from a since-changed network) is reported once and treated
    as length 0 rather than crashing the whole run."""
    lengths = {}
    missing = []
    for edge_id in set(edge_ids):
        try:
            lengths[edge_id] = net.getEdge(edge_id).getLength()
        except Exception:
            lengths[edge_id] = 0.0
            missing.append(edge_id)
    if missing:
        shown = ", ".join(sorted(missing)[:10])
        print(f"[WARN] {len(missing)} edge ID(s) not found in the network "
              f"(treated as length 0): {shown}" + (" ..." if len(missing) > 10 else ""))
    return lengths


def newson_krumm_accuracy(true_route, matched_route, net):
    """Compute Newson & Krumm's accuracy = (d+ + d-) / d0 between two
    ordered edge-ID routes, using a MULTISET (Counter) comparison so a
    route that legitimately revisits the same edge (a loop, a U-turn) is
    handled correctly rather than collapsed to a plain set.

    d0 = total length of the correct route
    d- = length of correct-route edge-visits the matched route is missing
    d+ = length of matched-route edge-visits that aren't on the correct route
    """
    true_counts = Counter(true_route)
    matched_counts = Counter(matched_route)

    all_ids = set(true_counts) | set(matched_counts)
    lengths = edge_lengths(net, all_ids)

    d0 = sum(lengths[e] * n for e, n in true_counts.items())
    d_minus = sum(
        lengths[e] * max(true_counts[e] - matched_counts.get(e, 0), 0)
        for e in true_counts
    )
    d_plus = sum(
        lengths[e] * max(matched_counts[e] - true_counts.get(e, 0), 0)
        for e in matched_counts
    )

    accuracy = (d_plus + d_minus) / d0 if d0 > 0 else float("inf")

    missed_edges = sorted(
        e for e in true_counts if matched_counts.get(e, 0) < true_counts[e]
    )
    extra_edges = sorted(
        e for e in matched_counts if matched_counts[e] > true_counts.get(e, 0)
    )

    return {
        "accuracy": accuracy,
        "d0": d0,
        "d_minus": d_minus,
        "d_plus": d_plus,
        "n_true_edges": len(true_counts),
        "n_matched_edges": len(matched_counts),
        "n_missed_edges": len(missed_edges),
        "n_extra_edges": len(extra_edges),
    }


def export_ground_truth_geometry(net, true_route, output_path):
    """Bonus utility: walk the ground-truth route's own edges through the
    network and write out each edge's shape as lat/lon, in route order.
    This is the 'GPS coordinates for each edge' you were missing -- built
    directly from the network geometry, no phone data involved. Handy
    for plotting the true route against the raw GPS trace; not used by
    the accuracy calculation above."""
    rows = []
    for seq, edge_id in enumerate(true_route):
        try:
            edge = net.getEdge(edge_id)
        except Exception as e:
            print(f"[WARN] Skipping '{edge_id}' in geometry export: {e}")
            continue
        for point_idx, (x, y) in enumerate(edge.getShape()):
            lon, lat = net.convertXY2LonLat(x, y)
            rows.append({
                "seq": seq, "edge_id": edge_id, "point_index": point_idx,
                "x": x, "y": y, "lon": lon, "lat": lat,
            })

    if not rows:
        print("[WARN] Nothing to export for ground-truth geometry.")
        return

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    print(f"[INFO] Ground-truth route geometry written to {output_path} "
          f"({len(rows)} shape points across {len(true_route)} edges)")


def main():
    net_file = NET_FILE
    if net_file is None:
        sumocfg_abs = _resolve(SUMOCFG)
        if not os.path.exists(sumocfg_abs):
            raise FileNotFoundError(f"SUMO config not found: {sumocfg_abs}")
        net_file = parse_sumocfg_for_netfile(sumocfg_abs)

    route_file_abs = _resolve(ROUTE_FILE)
    if not os.path.exists(route_file_abs):
        raise FileNotFoundError(f"Route file not found: {route_file_abs}")

    print(f"[INFO] Net file:    {net_file}")
    print(f"[INFO] Route file:  {route_file_abs}")

    print("[INFO] Loading network geometry with sumolib...")
    net = sumolib.net.readNet(net_file, withInternal=True)

    true_route = load_ground_truth_route(route_file_abs, ROUTE_ID)
    print(f"[INFO] Ground-truth route: {len(true_route)} edges "
          f"({len(set(true_route))} unique)")

    if EXPORT_GROUND_TRUTH_GEOMETRY:
        export_ground_truth_geometry(net, true_route, _resolve(GROUND_TRUTH_GEOMETRY_OUTPUT))

    results = {}
    for label, path in FILES.items():
        abs_path = _resolve(path)
        if not os.path.exists(abs_path):
            print(f"[WARN] {label}: file not found at {abs_path} -- skipping.")
            continue
        try:
            matched_route = edges_from_matched_csv(abs_path, EXCLUDE_INTERNAL_EDGES)
        except ValueError as e:
            print(f"[WARN] {label}: {e}")
            continue

        stats = newson_krumm_accuracy(true_route, matched_route, net)
        results[label] = stats

        print(f"\n=== {label} ({path}) ===")
        print(f"  matched route      : {stats['n_matched_edges']} distinct edges "
              f"({len(matched_route)} steps)")
        print(f"  d0 (correct route) : {stats['d0']:.1f} m")
        print(f"  d- (missed)        : {stats['d_minus']:.1f} m "
              f"({stats['n_missed_edges']} edges)")
        print(f"  d+ (extra)         : {stats['d_plus']:.1f} m "
              f"({stats['n_extra_edges']} edges)")
        print(f"  accuracy (d+ + d-)/d0 : {stats['accuracy']:.4f}")

    if not results:
        print("\n[WARN] No files produced usable results.")
        return

    print("\n" + "=" * 78)
    print(f"{'method':<16}{'d0 (m)':>10}{'d- (m)':>10}{'d+ (m)':>10}{'accuracy':>12}")
    print("-" * 78)
    for label, stats in results.items():
        print(f"{label:<16}{stats['d0']:>10.1f}{stats['d_minus']:>10.1f}"
              f"{stats['d_plus']:>10.1f}{stats['accuracy']:>12.4f}")
    print("=" * 78)

    if SUMMARY_OUTPUT:
        out_path = _resolve(SUMMARY_OUTPUT)
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["method", "d0_m", "d_minus_m", "d_plus_m", "accuracy",
                              "n_true_edges", "n_matched_edges",
                              "n_missed_edges", "n_extra_edges"])
            for label, stats in results.items():
                writer.writerow([label, stats["d0"], stats["d_minus"], stats["d_plus"],
                                  stats["accuracy"], stats["n_true_edges"],
                                  stats["n_matched_edges"], stats["n_missed_edges"],
                                  stats["n_extra_edges"]])
        print(f"\n[INFO] Summary written to {out_path}")


if __name__ == "__main__":
    main()
